services:
  cync-lan:
    container_name: cync-lan
    image: wnpick/cync-lan:latest
    restart: unless-stopped
    build:
      # clone the repo and from the repo base run: docker compose -f ./docker/Dockerfile build
      dockerfile: ./docker/Dockerfile
      context: ../
    ports:
      # port Cync devices connect to
      - "23779:23779"
      # local export server for cync-lan: http://localhost:23778 then click the 'start_export' button
      - "23778:23778"
    volumes:
      # Create a ./config dir and place an existing config file in this directory
      # if you change CYNC_BASE_DIR or CYNC_CONFIG_DIR then update the right side of the volume mapping to match the new path
      - ./config:/root/cync-lan/config
#    env_file: ./env
    environment:
      TZ: "America/Chicago"
      # to export devices from the cloud account, the export web app needs to be enabled and the cync username/password configured.
      # if you only want to use the LAN bridge functionality and don't need to export devices from the cloud account,
      # you can disable the exporter with this variable. If the exporter is enabled, you must configure the account username and password variables as well.
#      CYNC_ENABLE_EXPORTER: no
      # Credentials are required for the export web app to access your Cync account and retrieve device information,
      # but they are not required for the main LAN bridge functionality.
      CYNC_ACCOUNT_USERNAME: "cync-account-email@gmail.com"
      CYNC_ACCOUNT_PASSWORD: "cync-account-password"
      # Interface to listen for cync devices on, default is 0.0.0.0 but can be set to a specific IP if needed.
#      CYNC_SRV_HOST: "192.168.45.67"
      # Interface for the export server, default is 127.0.0.1, but can be set to a specific IP if needed.
#      CYNC_EXPORT_HOST: "192.168.97.65"

#      CYNC_MQTT_HOST: "homeassistant.local"
#      CYNC_MQTT_PORT: 1833
#      CYNC_MQTT_USER: "username"
#      CYNC_MQTT_PASS: "password"
#      CYNC_TOPIC: "cync_lan"
    # Debug logging, regular and raw binary
#      CYNC_DEBUG: yes
#      CYNC_RAW_DEBUG: yes
    networks:
      - cync-lan

networks:
    cync-lan:
        driver: bridge
